import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const KEY="github_cp_pro_v1",$=id=>document.getElementById(id);
let state=loadState(),ui={sort:"value",dir:"desc",sel:new Set(),offline:true},auth=null,db=null,user=null,firebaseReady=false,autoTimer=null,curHist=[],plHist=[];
const SECTORS={VHM:"Bất động sản",VIC:"Bất động sản",VRE:"Bất động sản",NVL:"Bất động sản",KDH:"Bất động sản",FPT:"Công nghệ thông tin",CMG:"Công nghệ thông tin",HPG:"Thép",HSG:"Thép",NKG:"Thép",VCB:"Ngân hàng",BID:"Ngân hàng",CTG:"Ngân hàng",TCB:"Ngân hàng",MBB:"Ngân hàng",ACB:"Ngân hàng",STB:"Ngân hàng",VPB:"Ngân hàng",HDB:"Ngân hàng",SHB:"Ngân hàng",ABB:"Ngân hàng",SSI:"Chứng khoán",VND:"Chứng khoán",HCM:"Chứng khoán",VCI:"Chứng khoán",MBS:"Chứng khoán",SHS:"Chứng khoán",GAS:"Dầu khí",PLX:"Dầu khí",PVD:"Dầu khí",PVS:"Dầu khí",VNM:"Thực phẩm - đồ uống",MSN:"Tiêu dùng",SAB:"Thực phẩm - đồ uống",MWG:"Bán lẻ",FRT:"Bán lẻ",DGW:"Bán lẻ",PNJ:"Bán lẻ",GMD:"Cảng biển - logistics",HAH:"Vận tải biển",REE:"Điện - nước",POW:"Điện",DGC:"Hóa chất",DCM:"Phân bón",DPM:"Phân bón"};
function base(){return{holdings:[],prices:{},history:{},snaps:[],settings:{providerOrder:"tcbs-yahoo",proxyMode:"none",proxyTemplate:"https://api.allorigins.win/raw?url={url}"}}}
function loadState(){try{return{...base(),...(JSON.parse(localStorage.getItem(KEY))||{})}}catch{return base()}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(state));status("Đã lưu local")}
function n(v){let x=Number(String(v??"").replace(/,/g,"").trim());return Number.isFinite(x)?x:0}
function money(v){return n(v).toLocaleString("vi-VN",{maximumFractionDigits:0})}
function pct(v){return(n(v)*100).toLocaleString("vi-VN",{maximumFractionDigits:2})+"%"}
function cls(v){return n(v)>=0?"good":"bad"} function clean(v){return String(v||"").trim().toUpperCase().replace(/[^A-Z0-9]/g,"")}
function status(t){$("status").textContent=t} function today(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function isFirebaseConfigured(){let s=JSON.stringify(firebaseConfig||{});return firebaseConfig?.apiKey&&firebaseConfig?.projectId&&firebaseConfig?.authDomain&&!s.includes("DAN_")}
function initFirebase(){try{if(!isFirebaseConfigured())throw Error("Chưa cấu hình Firebase. Có thể dùng offline.");const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);firebaseReady=true;onAuthStateChanged(auth,async u=>{user=u||null;if(u){ui.offline=false;$("auth").classList.add("hide");$("app").classList.remove("hide");$("userBadge").textContent=u.email||"Đã đăng nhập";await loadCloud();render();status("Đã đăng nhập")}else{$("auth").classList.remove("hide");$("app").classList.add("hide")}});$("authMsg").textContent="Firebase sẵn sàng."}catch(e){$("authMsg").textContent=e.message||String(e);firebaseReady=false}}
async function saveCloud(){saveLocal();if(!firebaseReady||!user||ui.offline){status("Đã lưu local");return}await setDoc(doc(db,"users",user.uid),{state,updatedAt:serverTimestamp()},{merge:true});status("Đã lưu đồng bộ")}
async function loadCloud(){if(!firebaseReady||!user)return;let s=await getDoc(doc(db,"users",user.uid));if(s.exists()&&s.data().state){state={...base(),...s.data().state};saveLocal()}else await saveCloud()}
function openOffline(){ui.offline=true;$("auth").classList.add("hide");$("app").classList.remove("hide");$("userBadge").textContent="Offline";render()}

function proxify(url){let m=state.settings.proxyMode;if(m==="allorigins")return "https://api.allorigins.win/raw?url="+encodeURIComponent(url);if(m==="custom"&&state.settings.proxyTemplate)return state.settings.proxyTemplate.replace("{url}",encodeURIComponent(url));return url}
async function fetchJson(url){let res=await fetch(proxify(url),{cache:"no-store"});let text=await res.text();if(!res.ok)throw Error("HTTP "+res.status);try{return JSON.parse(text)}catch{throw Error("Không parse được JSON")}}
function yahooSymbols(c,e){if(e==="HOSE")return[`${c}.VN`,`${c}.HM`];if(e==="HNX")return[`${c}.HN`,`${c}.VN`];if(e==="UPCOM")return[`${c}.HN`,`${c}.VN`,`${c}.UPCOM`];return[`${c}.VN`,`${c}.HM`,`${c}.HN`]}
function rangeFor(s,i){if(["1m","5m","15m"].includes(i))return s<=80?"1d":"5d";if(i==="1h")return s<=80?"1mo":"3mo";if(i==="1wk")return s<=50?"1y":"5y";if(i==="1mo")return"10y";return s<=20?"1mo":s<=50?"3mo":s<=120?"6mo":"1y"}
async function yahooHistory(c,e,s=50,i="1d"){let errs=[];for(let sym of yahooSymbols(c,e)){try{let url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?range=${rangeFor(s,i)}&interval=${i}`;let d=await fetchJson(url);let res=d?.chart?.result?.[0];if(!res)throw Error(`${sym}: no result`);let q=res.indicators?.quote?.[0]||{},ts=res.timestamp||[];let out=ts.map((t,k)=>{let dd=new Date(t*1000),date=(i==="1d"||i==="1wk"||i==="1mo")?dd.toISOString().slice(0,10):dd.toISOString().replace("T"," ").slice(0,16);return{date,open:n(q.open?.[k]),high:n(q.high?.[k]),low:n(q.low?.[k]),close:n(q.close?.[k]),volume:n(q.volume?.[k])}}).filter(x=>x.close>0).slice(-s);if(!out.length)throw Error(`${sym}: no bars`);return{source:`Yahoo:${sym}`,history:out,meta:res.meta||{}}}catch(e){errs.push(e.message)}}throw Error(errs.join(" | "))}
function tcbsRes(interval){if(interval==="1wk")return "W";if(interval==="1mo")return "M";if(interval==="1h")return "60";if(interval==="15m")return "15";if(interval==="5m")return "5";if(interval==="1m")return "1";return "D"}
function normalizeTCBS(raw){let arr=Array.isArray(raw)?raw:(raw.data||raw.Data||raw.bars||raw.items||[]);if(!Array.isArray(arr))return[];return arr.map(x=>{let ts=x.tradingDate||x.date||x.time||x.t||x.datetime;let date=typeof ts==="number"?new Date(ts*(ts>1e12?1:1000)).toISOString().slice(0,10):String(ts||"").slice(0,16);return{date,open:n(x.open??x.o),high:n(x.high??x.h),low:n(x.low??x.l),close:n(x.close??x.c),volume:n(x.volume??x.v)}}).filter(x=>x.date&&x.close>0).sort((a,b)=>a.date.localeCompare(b.date))}
async function tcbsHistory(c,e,s=50,i="1d"){let to=Math.floor(Date.now()/1000),from=to-86400*(s*4+20),res=tcbsRes(i);let urls=[`https://apipubaws.tcbs.com.vn/stock-insight/v1/stock/bars-long-term?ticker=${c}&type=stock&resolution=${res}&from=${from}&to=${to}`,`https://apipubaws.tcbs.com.vn/stock-insight/v1/stock/bars?ticker=${c}&type=stock&resolution=${res}&from=${from}&to=${to}`];let errs=[];for(let url of urls){try{let out=normalizeTCBS(await fetchJson(url)).slice(-s);if(out.length)return{source:"TCBS",history:out,meta:{}};throw Error("empty")}catch(e){errs.push(e.message)}}throw Error("TCBS: "+errs.join(" | "))}
async function fetchHistory(c,e,s=50,i="1d"){let order=state.settings.providerOrder==="yahoo-tcbs"?["yahoo","tcbs"]:state.settings.providerOrder==="tcbs"?["tcbs"]:state.settings.providerOrder==="yahoo"?["yahoo"]:["tcbs","yahoo"];let errs=[];for(let p of order){try{return p==="tcbs"?await tcbsHistory(c,e,s,i):await yahooHistory(c,e,s,i)}catch(e){errs.push(e.message)}}throw Error(errs.join(" || "))}
async function fetchPrice(h){let d=await fetchHistory(h.code,h.exchange,10,"1d"),a=d.history,last=a.at(-1),prev=a.at(-2),price=n(d.meta.regularMarketPrice)||last.close,prevClose=prev?prev.close:0;return{price,prevClose,change:prevClose?price-prevClose:0,volume:n(d.meta.regularMarketVolume)||last.volume,date:last.date,source:d.source}}
async function fetchPrices(){if(!state.holdings.length)return status("Chưa có danh mục");$("fetchPricesBtn").disabled=true;status("Đang fetch giá...");let ok=0,fail=[];for(let h of state.holdings){try{state.prices[h.code]=await fetchPrice(h);ok++}catch(e){console.warn(e);fail.push(h.code)}}await saveCloud();render();status(fail.length?`Fetch ${ok} mã, lỗi: ${fail.join(", ")}`:`Fetch xong ${ok} mã`);$("fetchPricesBtn").disabled=false}
function toggleAuto(){if(autoTimer){clearInterval(autoTimer);autoTimer=null;$("autoBtn").textContent="Bật auto 60s";$("autoBtn").className="gray";status("Đã tắt auto")}else{fetchPrices();autoTimer=setInterval(fetchPrices,60000);$("autoBtn").textContent="Tắt auto";$("autoBtn").className="red";status("Đã bật auto")}}
function pObj(h){return state.prices[h.code]||{price:n(h.manualPrice),prevClose:0,volume:0,source:"Thủ công"}}
function row(h){let p=pObj(h),price=n(p.price),prev=n(p.prevClose),chg=prev?price-prev:n(p.change),cost=n(h.qty)*n(h.cost),val=n(h.qty)*price,pl=val-cost;return{h,p,price,prev,chg,cost,val,pl,plPct:cost?pl/cost:0,day:n(h.qty)*chg,dayPct:prev?chg/prev:0,vol:n(p.volume),weight:0}}
function rows(){let a=state.holdings.map(row),tv=a.reduce((s,r)=>s+r.val,0);a.forEach(r=>r.weight=tv?r.val/tv:0);return a}
function total(a=rows()){return a.reduce((o,r)=>(o.cost+=r.cost,o.val+=r.val,o.pl+=r.pl,o.day+=r.day,o),{cost:0,val:0,pl:0,day:0})}
function filtered(){let a=rows(),sec=$("sectorFilter").value;if(sec)a=a.filter(r=>r.h.sector===sec);let dir=ui.dir==="asc"?1:-1,k=ui.sort;a.sort((x,y)=>{let vx=sv(x,k),vy=sv(y,k);return typeof vx==="string"?vx.localeCompare(String(vy))*dir:(n(vx)-n(vy))*dir});return a}
function sv(r,k){return k==="code"?r.h.code:k==="sector"?r.h.sector:k==="qty"?r.h.qty:k==="cost"?r.h.cost:k==="price"?r.price:k==="value"?r.val:k==="pl"?r.pl:k==="weight"?r.weight:r[k]}
function render(){fill();metrics();table();priceEditor();dashboard();details();snaps();analytics();chosen();settingsUI()}
function fill(){let opts=[["value","Giá trị"],["weight","Tỷ trọng"],["pl","Lãi/lỗ"],["code","Mã"],["sector","Ngành"],["price","Giá"],["qty","SL"],["cost","Giá vốn"]];$("sortSelect").innerHTML=opts.map(o=>`<option value="${o[0]}" ${ui.sort===o[0]?"selected":""}>${o[1]}</option>`).join("");$("sortDir").value=ui.dir;let secs=[...new Set(state.holdings.map(h=>h.sector||"Chưa rõ"))].sort();for(let id of["sectorFilter","historySector"]){let el=$(id),cur=el.value;el.innerHTML='<option value="">Tất cả</option>'+secs.map(s=>`<option value="${s}">${s}</option>`).join("");el.value=secs.includes(cur)?cur:""}}
function metrics(){let a=rows(),t=total(a),tp=t.cost?t.pl/t.cost:0,dp=(t.val-t.day)?t.day/(t.val-t.day):0;$("mCost").textContent=money(t.cost);$("mValue").textContent=money(t.val);$("mPL").textContent=money(t.pl);$("mPL").className="value "+cls(t.pl);$("mPLPct").textContent=pct(tp);$("mDay").textContent=money(t.day);$("mDay").className="value "+cls(t.day);$("mDayPct").textContent=pct(dp);$("mCount").textContent=a.length;let top=[...a].sort((x,y)=>y.weight-x.weight);$("mTop3").textContent=pct(top.slice(0,3).reduce((s,r)=>s+r.weight,0));let best=[...a].sort((x,y)=>y.pl-x.pl)[0],worst=[...a].sort((x,y)=>x.pl-y.pl)[0];$("mBest").textContent=best?`${best.h.code} ${money(best.pl)}`:"-";$("mBest").className="value "+(best?cls(best.pl):"");$("mWorst").textContent=worst?`${worst.h.code} ${money(worst.pl)}`:"-";$("mWorst").className="value "+(worst?cls(worst.pl):"")}
function table(){$("holdingsBody").innerHTML=filtered().map(r=>`<tr class="${ui.sel.has(r.h.code)?"selected-row":""}"><td class="left"><input type="checkbox" data-sel="${r.h.code}" ${ui.sel.has(r.h.code)?"checked":""}></td><td class="left"><b>${r.h.code}</b><br><button class="ghost" data-hist="${r.h.code}">Lịch sử</button></td><td>${r.h.exchange}</td><td class="left">${r.h.sector}</td><td>${money(r.h.qty)}</td><td>${money(r.h.cost)}</td><td>${r.price?money(r.price):'<span class="amber">Chưa có</span>'}</td><td>${r.prev?money(r.prev):"-"}</td><td>${money(r.val)}</td><td>${pct(r.weight)}</td><td class="${cls(r.pl)}">${money(r.pl)}</td><td class="${cls(r.pl)}">${pct(r.plPct)}</td><td class="${cls(r.day)}">${money(r.day)}</td><td>${r.vol?money(r.vol):"-"}</td><td>${r.p.source||"-"}</td><td><button class="ghost" data-edit="${r.h.code}">Sửa</button> <button class="red" data-del="${r.h.code}">Xóa</button></td></tr>`).join("");document.querySelectorAll("[data-sel]").forEach(e=>e.onchange=()=>{e.checked?ui.sel.add(e.dataset.sel):ui.sel.delete(e.dataset.sel);render()});document.querySelectorAll("[data-hist]").forEach(e=>e.onclick=()=>openHist(e.dataset.hist));document.querySelectorAll("[data-edit]").forEach(e=>e.onclick=()=>edit(e.dataset.edit));document.querySelectorAll("[data-del]").forEach(e=>e.onclick=()=>del(e.dataset.del))}
function priceEditor(){$("priceEditBody").innerHTML=state.holdings.map(h=>{let p=pObj(h);return`<tr><td><b>${h.code}</b></td><td><input data-price="${h.code}" type="number" value="${p.price||""}"></td><td><input data-prev="${h.code}" type="number" value="${p.prevClose||""}"></td><td><input data-vol="${h.code}" type="number" value="${p.volume||""}"></td><td><input data-date="${h.code}" value="${p.date||today()}"></td><td><button data-saveprice="${h.code}">Lưu</button></td></tr>`}).join("");document.querySelectorAll("[data-saveprice]").forEach(b=>b.onclick=()=>{let c=b.dataset.saveprice;state.prices[c]={price:n(document.querySelector(`[data-price="${c}"]`).value),prevClose:n(document.querySelector(`[data-prev="${c}"]`).value),volume:n(document.querySelector(`[data-vol="${c}"]`).value),date:document.querySelector(`[data-date="${c}"]`).value,source:"Thủ công"};let h=state.holdings.find(x=>x.code===c);if(h)h.manualPrice=state.prices[c].price;saveCloud();render()})}
function dashboard(){drawLine("navChart",state.snaps,x=>n(x.val),"NAV");drawPie("sectorChart",sectorDist(),"Ngành");$("topBody").innerHTML=[...rows()].sort((a,b)=>b.weight-a.weight).slice(0,10).map(r=>`<tr><td><b>${r.h.code}</b></td><td>${r.h.sector}</td><td>${money(r.val)}</td><td>${pct(r.weight)}</td><td class="${cls(r.pl)}">${money(r.pl)}</td></tr>`).join("")}
function details(){let cur=$("detailSelect").value;$("detailSelect").innerHTML=state.holdings.map(h=>`<option>${h.code}</option>`).join("");if(state.holdings.some(h=>h.code===cur))$("detailSelect").value=cur}
function snaps(){$("snapshotBody").innerHTML=state.snaps.slice().reverse().map(r=>`<tr><td>${r.date}</td><td>${money(r.val)}</td><td class="${cls(r.pl)}">${money(r.pl)}</td><td class="${cls(r.pl)}">${pct(r.plPct)}</td><td class="${cls(r.day)}">${money(r.day)}</td></tr>`).join("");drawLine("navChart2",state.snaps,x=>n(x.val),"NAV")}
function analytics(){drawPie("sectorChart2",sectorDist(),"Ngành");drawBars("plBarChart",[...rows()].sort((a,b)=>b.pl-a.pl).slice(0,12),x=>x.pl,"Lãi/lỗ",x=>x.h.code,true);drawBars("weightBarChart",[...rows()].sort((a,b)=>b.weight-a.weight).slice(0,12),x=>x.weight*100,"Tỷ trọng %",x=>x.h.code,false);let t=total(),top=[...rows()].sort((a,b)=>b.weight-a.weight);$("analyticsBody").innerHTML=[["Tổng vốn",money(t.cost),"Tổng vốn"],["Tổng giá trị",money(t.val),"Theo giá hiện tại"],["Lãi/lỗ",`${money(t.pl)} (${pct(t.cost?t.pl/t.cost:0)})`,"Theo giá vốn"],["Top 3 tỷ trọng",pct(top.slice(0,3).reduce((s,r)=>s+r.weight,0)),"Rủi ro tập trung"],["Số ngành",sectorDist().length,"Theo danh mục"]].map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td class="left">${x[2]}</td></tr>`).join("")}
function settingsUI(){$("providerOrder").value=state.settings.providerOrder;$("proxyMode").value=state.settings.proxyMode;$("proxyTemplate").value=state.settings.proxyTemplate}
function chosen(){let list=getPLHoldings();$("chosenChips").innerHTML=list.map(h=>`<span class="chip">${h.code} · ${h.sector}</span>`).join("")}
function sectorDist(){let m=new Map();for(let r of rows())m.set(r.h.sector,(m.get(r.h.sector)||0)+r.val);return[...m.entries()].map(([label,value])=>({label,value})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value)}
async function add(){let code=clean($("code").value),exchange=$("ex").value,sector=$("sec").value.trim()||SECTORS[code]||"Chưa rõ",qty=n($("qty").value),cost=n($("cost").value),manualPrice=n($("manual").value);if(!code||qty<=0||cost<=0)return alert("Nhập mã, SL, giá vốn");let old=state.holdings.find(h=>h.code===code),obj={code,exchange,sector,qty,cost,manualPrice};if(old)Object.assign(old,obj);else state.holdings.push(obj);if(manualPrice)state.prices[code]={price:manualPrice,prevClose:n(state.prices[code]?.prevClose),volume:n(state.prices[code]?.volume),date:today(),source:"Thủ công"};["code","sec","qty","cost","manual"].forEach(id=>$(id).value="");await saveCloud();render()}
function edit(c){let h=state.holdings.find(x=>x.code===c);if(!h)return;$("code").value=h.code;$("ex").value=h.exchange;$("sec").value=h.sector;$("qty").value=h.qty;$("cost").value=h.cost;$("manual").value=h.manualPrice||pObj(h).price||"";tab("port");scrollTo({top:0,behavior:"smooth"})}
async function del(c){if(confirm("Xóa "+c+"?")){state.holdings=state.holdings.filter(h=>h.code!==c);delete state.prices[c];delete state.history[c];ui.sel.delete(c);await saveCloud();render()}}
async function saveSnap(){let t=total();if(!t.val)return alert("Chưa có giá");let r={date:today(),cost:t.cost,val:t.val,pl:t.pl,plPct:t.cost?t.pl/t.cost:0,day:t.day};let i=state.snaps.findIndex(x=>x.date===r.date);if(i>=0)state.snaps[i]=r;else state.snaps.push(r);await saveCloud();render()}
function importPriceCsv(){parseCsv($("priceCsv").value).forEach(r=>{let c=clean(r.code||r[0]);if(!c)return;state.prices[c]={price:n(r.price||r[1]),prevClose:n(r.prevClose||r[2]),volume:n(r.volume||r[3]),date:r.date||r[4]||today(),source:"CSV"};let h=state.holdings.find(x=>x.code===c);if(h)h.manualPrice=state.prices[c].price});saveCloud();render()}
function importHistCSV(){let count=0;parseCsv($("historyCsv").value).forEach(r=>{let c=clean(r.code||r[0]);if(!c)return;state.history[c]=state.history[c]||[];let row={date:r.date||r[1],open:n(r.open||r[2]),high:n(r.high||r[3]),low:n(r.low||r[4]),close:n(r.close||r[5]),volume:n(r.volume||r[6])};if(row.date&&row.close){let i=state.history[c].findIndex(x=>x.date===row.date);if(i>=0)state.history[c][i]=row;else state.history[c].push(row);count++}});Object.keys(state.history).forEach(c=>state.history[c].sort((a,b)=>a.date.localeCompare(b.date)));saveCloud();render();alert("Đã nhập "+count+" dòng")}
function parseCsv(t){let lines=t.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];let headers=lines[0].split(",").map(x=>x.trim()),has=headers.some(h=>["code","date","close","price"].includes(h));return lines.slice(has?1:0).map(line=>{let vals=line.split(",").map(x=>x.trim());if(!has)return vals;let o={};headers.forEach((h,i)=>o[h]=vals[i]);return o})}
function openHist(c){$("detailSelect").value=c;tab("stock");loadHist()}
async function loadHist(){let c=$("detailSelect").value;if(!c)return;let h=state.holdings.find(x=>x.code===c),s=n($("stockSessions").value)||50,i=$("interval").value;status("Đang fetch lịch sử...");try{let d=await fetchHistory(c,h.exchange,s,i);curHist=d.history;state.history[c]=merge(state.history[c]||[],curHist);await saveCloud();$("detailMsg").textContent=`Nguồn: ${d.source}. Fetch ${curHist.length} dòng.`}catch(e){curHist=(state.history[c]||[]).slice(-s);$("detailMsg").textContent=`Fetch lỗi: ${e.message||e}. Dùng dữ liệu local nếu có.`}stockStats();drawLine("priceChart",curHist,x=>x.close,"Giá "+c);drawBars("volumeChart",curHist,x=>x.volume,"KL "+c,x=>x.date,false);$("stockHistoryBody").innerHTML=curHist.slice().reverse().map((x,idx,arr)=>{let prev=arr[idx+1]?.close,ret=prev?x.close/prev-1:0;return`<tr><td>${x.date}</td><td>${money(x.open)}</td><td>${money(x.high)}</td><td>${money(x.low)}</td><td>${money(x.close)}</td><td>${money(x.volume)}</td><td class="${cls(ret)}">${prev?pct(ret):"-"}</td></tr>`}).join("");status("Xong")}
function merge(a,b){let m=new Map();[...a,...b].forEach(x=>m.set(x.date,x));return[...m.values()].sort((x,y)=>x.date.localeCompare(y.date))}
function stockStats(){let c=curHist.map(x=>n(x.close)).filter(Boolean),h=curHist.map(x=>n(x.high)).filter(Boolean),l=curHist.map(x=>n(x.low)).filter(Boolean),v=curHist.map(x=>n(x.volume));$("dPrice").textContent=c.length?money(c.at(-1)):"-";$("dHigh").textContent=h.length?money(Math.max(...h)):"-";$("dLow").textContent=l.length?money(Math.min(...l)):"-";$("dAvg").textContent=c.length?money(c.reduce((s,x)=>s+x,0)/c.length):"-";$("dVol").textContent=money(v.reduce((s,x)=>s+x,0));$("dAvgVol").textContent=v.length?money(v.reduce((s,x)=>s+x,0)/v.length):"-";let ret=c.length>1?c.at(-1)/c[0]-1:0;$("dRet").textContent=c.length>1?pct(ret):"-";$("dRet").className="value "+cls(ret);$("dRange").textContent=h.length&&l.length?pct((Math.max(...h)-Math.min(...l))/Math.min(...l)):"-"}
function getPLHoldings(){let chosen=[...ui.sel];if(chosen.length)return state.holdings.filter(h=>ui.sel.has(h.code));let sec=$("historySector").value;if(sec)return state.holdings.filter(h=>h.sector===sec);return state.holdings}
function calcPL(){let list=getPLHoldings(),s=n($("portfolioSessions").value)||50,cost=list.reduce((sum,h)=>sum+n(h.qty)*n(h.cost),0),dates=[...new Set(list.flatMap(h=>(state.history[h.code]||[]).map(x=>x.date)))].sort().slice(-s);plHist=dates.map(date=>{let val=0,cov=0;for(let h of list){let bar=(state.history[h.code]||[]).find(x=>x.date===date);if(bar){val+=n(h.qty)*n(bar.close);cov++}}return{date,val,cost,pl:val-cost,plPct:cost?(val-cost)/cost:0,cov}}).filter(x=>x.cov);let vals=plHist.map(x=>x.val),last=plHist.at(-1);drawLine("portfolioChart",plHist,x=>x.val,"NAV");drawLine("portfolioPLChart",plHist,x=>x.pl,"Lãi/lỗ");$("portfolioHistoryBody").innerHTML=plHist.slice().reverse().map(r=>`<tr><td>${r.date}</td><td>${money(r.val)}</td><td>${money(r.cost)}</td><td class="${cls(r.pl)}">${money(r.pl)}</td><td class="${cls(r.pl)}">${pct(r.plPct)}</td><td>${r.cov}/${list.length}</td></tr>`).join("");$("pCost").textContent=money(cost);$("pNav").textContent=last?money(last.val):"-";$("pPL").textContent=last?money(last.pl):"-";$("pPL").className="value "+(last?cls(last.pl):"");$("pPct").textContent=last?pct(last.plPct):"-";$("pHigh").textContent=vals.length?money(Math.max(...vals)):"-";$("pLow").textContent=vals.length?money(Math.min(...vals)):"-";$("pN").textContent=plHist.length;$("pDD").textContent=vals.length?pct(maxDD(vals)):"-";$("portfolioMsg").textContent=plHist.length?"Đã tính từ lịch sử đã fetch/import.":"Chưa có lịch sử."}
function maxDD(vals){let peak=vals[0]||0,m=0;for(let v of vals){if(v>peak)peak=v;if(peak)m=Math.min(m,v/peak-1)}return m}
function axes(ctx,c,pad,min,max,label){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#667085";ctx.font="13px system-ui";ctx.strokeStyle="#e4e7ec";if(!isFinite(min)||!isFinite(max)){min=0;max=1}if(min===max){min*=.98;max=max*1.02+1}for(let i=0;i<5;i++){let y=pad+i*(c.height-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(c.width-pad,y);ctx.stroke();ctx.fillText(money(max-(max-min)*i/4),6,y+4)}ctx.fillStyle="#101828";ctx.font="14px system-ui";ctx.fillText(label,pad,20)}
function drawLine(id,data,get,label){let c=$(id);if(!c)return;let ctx=c.getContext("2d"),pad=54;if(!data||!data.length){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#667085";ctx.fillText("Chưa có dữ liệu.",24,40);return}let vals=data.map(get),min=Math.min(...vals),max=Math.max(...vals);axes(ctx,c,pad,min,max,label);let w=c.width-pad*2,h=c.height-pad*2,x=i=>pad+i*w/Math.max(1,data.length-1),y=v=>pad+h-((v-min)/((max-min)||1))*h;ctx.strokeStyle="#0f766e";ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>i?ctx.lineTo(x(i),y(get(d))):ctx.moveTo(x(i),y(get(d))));ctx.stroke();ctx.fillStyle="#101828";let last=data.at(-1);ctx.fillText(`${last.date||""}: ${money(get(last))}`,pad,c.height-12)}
function drawBars(id,data,get,label,getLabel=x=>x.label,allowNeg=false){let c=$(id);if(!c)return;let ctx=c.getContext("2d"),pad=54;if(!data||!data.length){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle="#667085";ctx.fillText("Chưa có dữ liệu.",24,40);return}let vals=data.map(get),min=allowNeg?Math.min(0,...vals):0,max=Math.max(...vals,1);axes(ctx,c,pad,min,max,label);let w=c.width-pad*2,h=c.height-pad*2,bw=Math.max(3,w/data.length*.62),y=v=>pad+h-((v-min)/((max-min)||1))*h,zero=y(0);data.forEach((d,i)=>{let v=get(d),x=pad+i*w/data.length,bh=Math.abs(y(v)-zero);ctx.fillStyle=v>=0?"#0f766e":"#dc2626";ctx.fillRect(x,v>=0?y(v):zero,bw,bh)})}
function drawPie(id,data,label){let c=$(id);if(!c)return;let ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);if(!data.length){ctx.fillStyle="#667085";ctx.fillText("Chưa có dữ liệu.",24,40);return}let total=data.reduce((s,x)=>s+x.value,0),cx=c.width*.35,cy=c.height*.52,r=Math.min(c.width,c.height)*.28,colors=["#0f766e","#2563eb","#7c3aed","#dc2626","#b45309","#16a34a","#0891b2","#be123c"];let a=-Math.PI/2;data.slice(0,8).forEach((d,i)=>{let ang=d.value/total*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,a+ang);ctx.fillStyle=colors[i%colors.length];ctx.fill();a+=ang});ctx.fillStyle="#101828";ctx.font="14px system-ui";ctx.fillText(label,20,22);let y=34;data.slice(0,8).forEach((d,i)=>{ctx.fillStyle=colors[i%colors.length];ctx.fillRect(c.width*.62,y-10,12,12);ctx.fillStyle="#101828";ctx.fillText(`${d.label}: ${pct(d.value/total)}`,c.width*.62+18,y);y+=22})}
function tab(name){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));document.querySelectorAll(".sec").forEach(s=>s.classList.toggle("active",s.id===name));if(name==="ana")analytics();if(name==="dash")dashboard();if(name==="set")snaps()}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="danh-muc-cp-github-pro-backup.json";a.click();URL.revokeObjectURL(a.href)}
function importData(f){let r=new FileReader();r.onload=()=>{try{state={...base(),...JSON.parse(r.result)};saveCloud();render();alert("Đã nhập backup")}catch{alert("File không đúng định dạng")}};r.readAsText(f)}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$("login").onclick=async()=>{if(!firebaseReady)return $("authMsg").textContent="Firebase chưa sẵn sàng, hãy dùng offline hoặc kiểm tra config.";try{await signInWithEmailAndPassword(auth,$("email").value.trim(),$("pw").value)}catch(e){$("authMsg").textContent=e.message||e}};$("reg").onclick=async()=>{if(!firebaseReady)return $("authMsg").textContent="Firebase chưa sẵn sàng, hãy dùng offline hoặc kiểm tra config.";try{await createUserWithEmailAndPassword(auth,$("email").value.trim(),$("pw").value)}catch(e){$("authMsg").textContent=e.message||e}};$("offline").onclick=openOffline;$("logout").onclick=async()=>{if(firebaseReady&&auth&&!ui.offline)await signOut(auth);else location.reload()};$("fetchAll").onclick=fetchPrices;$("autoBtn").onclick=toggleAuto;$("save").onclick=saveCloud;$("forceSave").onclick=saveCloud;$("forceLoad").onclick=async()=>{await loadCloud();render()};$("snap").onclick=saveSnap;$("add").onclick=add;$("sortSelect").onchange=e=>{ui.sort=e.target.value;render()};$("sortDir").onchange=e=>{ui.dir=e.target.value;render()};$("sectorFilter").onchange=render;$("historySector").onchange=chosen;document.querySelectorAll("th.sortable").forEach(th=>th.onclick=()=>{let k=th.dataset.sort;if(ui.sort===k)ui.dir=ui.dir==="asc"?"desc":"asc";else{ui.sort=k;ui.dir="desc"}render()});$("clearSelectionBtn").onclick=()=>{ui.sel.clear();render()};$("saveSettings").onclick=()=>{state.settings.providerOrder=$("order").value;state.settings.proxyMode=$("proxy").value;state.settings.proxyTemplate=$("proxyTpl").value;saveCloud();render()};$("importPriceCsv").onclick=importPriceCsv;$("importHistCsv").onclick=importHistCSV;$("loadHist").onclick=loadHist;$("calcPL").onclick=calcPL;$("export").onclick=exportData;$("export2").onclick=exportData;$("import").onclick=()=>$("file").click();$("import2").onclick=()=>$("file").click();$("file").onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$("clearSnap").onclick=()=>{if(confirm("Xóa snapshot?")){state.snaps=[];saveCloud();render()}};$("clearAll").onclick=()=>{if(confirm("Xóa dữ liệu local?")){state=base();saveLocal();render()}}}
bind();initFirebase();render();
